### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by deepesh-agarwal** [sgjava/install-opencv#5]
Using the current official Ubuntu image on ODROID-C1+ I am unable to install OpenCV using your script. The log is as below:
```
[ 33%] Built target opencv_shape_pch_dephelp
[ 35%] Built target pch_Generate_opencv_shape
[ 36%] Built target opencv_shape
[ 38%] Built target opencv_videoio_pch_dephelp
[ 39%] Built target pch_Generate_opencv_videoio
Linking CXX shared library ../../lib/libopencv_videoio.so
/usr/bin/ld.bfd.real: /usr/local/lib/libavcodec.a(avpacket.o): relocation R_ARM_THM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libavcodec.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libopencv_videoio.so.3.0.0] Error 1
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make: *** [all] Error 2
10-26-2015 21:12:18 Removing /home/odroid/temp
10-26-2015 21:12:20 Elapse time: 00:27:46
```

**Comment by sgjava** [comment]
Try using 3.0.0 tag instead of master. Edit config-opencv.sh and change opencvcmd to "git clone --depth 1 -b 3.0.0 https://github.com/Itseez/opencv.git". Let me know if that works. I'm not able to test on an ODROID until this weekend with the master branch.

Secondly, I build Ubuntu with https://github.com/sgjava/ubuntu-mini#create-ubuntu-root-filesystem-odroid-c1c1, so there could be a difference betweenthe  official image and using Ubuntu minimal.

**Comment by sgjava** [comment]
This error indicates you may have ffmpeg installed as a static lib. Look at http://code.opencv.org/issues/4210. I'm using libav now instead of ffmpeg as is suggested for OpenCV on Ubuntu. Please remove static ffmpeg or try a different Ubuntu distribution. I was able to build current master branch fine on ODROID C1+.
